### ISSUE TITLE
Load from .mca

### ISSUE THREAD

**Issue by codingMASTER398** [PrismarineJS/prismarine-chunk#115]
Hi there!

I have a plan to make a program to make a one-command-block creation from a Minecraft world.
For that, I need to read the world that the original creation was made in.
This would be perfect for what I'm doing, but you can only create new chunks, not load any from a .mca file.
Can you add support for that?
![image](https://user-images.githubusercontent.com/55938439/115955462-e0e8bc80-a539-11eb-872e-ee42bcd54696.png)

**Comment by extremeheat** [comment]
see https://github.com/PrismarineJS/prismarine-provider-anvil/

```js
new Anvil(pathToRegionFolder).getRegion(chunkX, chunkZ)
```

if you want to get the region file directly, `chunkX = regionX << 5` & `chunkZ = regionZ << 5`

**Comment by codingMASTER398** [comment]
Thank you! this is a big help!
