### ISSUE TITLE
MCPE 1.18

### ISSUE THREAD

**Issue by Picoseconds** [PrismarineJS/prismarine-chunk#152]
Will this repo be updated to add support for MCPE 1.18 chunks? The format should be somewhat similar to the format stored in the level files.

**Comment by nickelpro** [comment]
We would very much like to support new Bedrock Edition chunk formats, but there is no documentation on the byte array layout for Bedrock chunk packets.

I'm certain the reverse engineering work has already been done for other 3rd party Bedrock code, so if you want to write the docs and integrate them into https://wiki.vg that would be a great boon to the community.

Or you can just PR new Bedrock chunk format code, that works too.

**Comment by extremeheat** [comment]
Happening in https://github.com/PrismarineJS/bedrock-provider/pull/9/, which handles the disk and network formats

Eventually this can be moved into pchunk or pchunk can dep from there.

The format used on Bedrock is quite different overall, and blocks can also be stored across [4-dimensions](https://gist.github.com/Tomcc/a96af509e275b1af483b25c543cfbf37) (x, y, z, and layer) which is how waterlogged/snowy blocks are handled opposed to mcpc where each block has a "waterlogged" or snowy tag on top of each block. Implemented behind the scenes with multiple block data stores. So these are some relatively minor things which need to be handled somehow when we do move it here.

**Comment by rom1504** [comment]
Would definitely appreciate to integrate bedrock-provider feature here
That would help make it more natural to expand mineflayer to bedrock

**Comment by extremeheat** [comment]
Wrote some basic docs for chunk serialization on disk/network in https://github.com/PrismarineJS/bedrock-provider/wiki/Minecraft-serialization and https://wiki.vg/Bedrock_Edition_level_format

It's not a lot (excludes biome information) but has the basic information around block data and network packet flow.
