### ISSUE TITLE
Benchmark this package

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/prismarine-chunk#18]
I think this might actually be the cursor computing/buffer getting that's making prismarine-world a bit slower than it could be.
(for generation when a lot of setBlock are done, and for physics when a lot of getBlock are done)

Once benchmarked, it would be interesting to compare different approaches (see https://github.com/PrismarineJS/prismarine-chunk/issues/16#issuecomment-147786153)

**Comment by rom1504** [comment]
kind of done

**Comment by Karang** [comment]
This can be closed ?

**Comment by rom1504** [comment]
Do you mean the tests ?
If they are good benchmarks, let's maybe just indicate it in the readme

**Comment by rom1504** [comment]
good enough
