### ISSUE TITLE
The value of "offset" is out of range. It must be >= 0 and <= 10239. Received 10684

### ISSUE THREAD

**Issue by SpikeThatMike** [PrismarineJS/prismarine-chunk#186]
The bot is crashing when joining the server. I dont have the exact code this is happening with.
However, I do know that this is being caused by a sign in the nether, which when destroyed it the bot wont crash while logging in, when replaced it will crash

stacktrace
https://sourceb.in/1iB0fA68TD

**Comment by nickelpro** [comment]
1.8 bug?

Can this be reproduced with a vanilla 1.8 server? If so we'll need a dump of the offending chunk

**Comment by nickelpro** [comment]
I think something weirder with the 1.8 protocol implementation is happening than pris-chunk is involved with. Placing a sign should not invoke the chunk parsing code, it should be a block change packet unless I'm missing something about how 1.8 handles block changes in the nether.

**Comment by nickelpro** [comment]
No wait, that is a single block change, something weird on our end then

**Comment by akiyuee** [comment]
It also happens on 1.12.2, both Vanilla and Paper.

I didn't even do anything to the world. It was freshly generated.

**Comment by extremeheat** [comment]
Can't reproduce on vanilla 1.8. Don't see anything obviously wrong with the code, links are
* update_sign packet https://github.com/PrismarineJS/mineflayer/blob/master/lib/plugins/blocks.js#L406
* chunk column light update https://github.com/PrismarineJS/prismarine-chunk/blob/master/src/pc/1.8/chunk.js#L143
* section https://github.com/PrismarineJS/prismarine-chunk/blob/master/src/pc/1.8/section.js#L121

if you can reproduce, providing packet structure of update_sign would be helpful, 
```js
bot._client.on('update_sign', console.log)
```

**Comment by nickelpro** [comment]
There's certainly something wrong overall with how we're handling block changes in 1.8, we get constant vague issues about it, and I think it might have something to do with signs, but I've got no insight past that.

**Comment by Taxalo** [comment]
Try on another world like the nether. That was the world where it crashed when placing a sign https://github.com/PrismarineJS/mineflayer/issues/2614#issuecomment-1117509648
