### ISSUE TITLE
Support both 1.8 and 1.9 chunk format

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/prismarine-chunk#19]
http://wiki.vg/SMP_Map_Format#Format

http://wiki.vg/Pre-release_protocol#Chunk_Section

https://github.com/PrismarineJS/node-minecraft-protocol/issues/231#issuecomment-186531996

This will help mineflayer and flying-squid update to cross-version (1.8 + 1.9)

**Comment by rom1504** [comment]
this will be useful https://gist.github.com/Gjum/0375b643ec13a42ab3c0#file-chunk_-5_5-dump

**Comment by rom1504** [comment]
see https://github.com/SpockBotMC/SpockBot/pull/218/files

**Comment by Gjum** [comment]
C implementation https://github.com/JavaProphet/MinecraftClone/blob/245fca26f1911ff87c04ac774079acb60546e78a/MinecraftClone/src/ingame.c#L201

**Comment by rom1504** [comment]
https://github.com/Steveice10/MCProtocolLib/blob/4ed72deb75f2acb0a81d641717b7b8074730f701/src/main/java/org/spacehq/mc/protocol/data/game/chunk/BlockStorage.java

**Comment by rom1504** [comment]
@mhsjlw has started working on that at https://github.com/mhsjlw/prismarine-nbt

**Comment by louwers** [comment]
Did the chunk format change in 1.10?

**Comment by mhsjlw** [comment]
Nope, not yet :smile:. I doubt the chunk format will change again for a very, very long time as this is probably the most optimized chunk format we've seen (hence how complicated it is, especially in JavaScript).

**Comment by louwers** [comment]
Here is another implementation in C: https://github.com/broese/mcbuild/blob/master/mcp_packet.c#L625

@mhsjlw This kind of stuff looks quite odd in Javascript, but why is it more difficult? Hard to get good performance?

**Comment by mhsjlw** [comment]
No, JavaScript doesn't natively support longs which the 1.9 chunk relies on, we've tried ways around it that seem to be successful, but we're not anywhere close.

**Comment by louwers** [comment]
What are still currently problems with your implementation?

**Comment by rom1504** [comment]
http://lunarco.de/minecraft/chunks/

**Comment by rom1504** [comment]
or https://download.rom1504.fr/minecraft/chunks/

**Comment by rom1504** [comment]
WIP there https://gist.github.com/rom1504/2d6451dbea299099b861ac6acef6ef7d

**Comment by polkovnikov-ph** [comment]
@rom1504 I don't understand the issue with `long`s at all. It's getting split into variable length bit fields anyway, there's no difference in the underlying datatype except that `count` always gets multiplied by 4. To circumvent the issues with computing the size, it's handy to create a structure with two u32 fields.

**Comment by Gjum** [comment]
The problem lies in accessing the data on these longs. Each entry is offset by some number of bits and can be split across two longs in a nontrivial way: http://wiki.vg/SMP_Map_Format#Example

**Comment by polkovnikov-ph** [comment]
@Gjum And what is the problem?

http://ideone.com/1pjC7Q

**Comment by rom1504** [comment]
@polkovnikov-ph the problem is nobody finished a full implementation for prismarine-chunk 1.9
mhsjw has started one at https://github.com/mhsjlw/prismarine-chunk but it's not quite working
So I started a new one recently from scratch, current code is at https://gist.github.com/rom1504/2d6451dbea299099b861ac6acef6ef7d
But I don't have a lot of time to work on this these days so it's not done yet.

I you feel like implementing it, go ahead !

**Comment by rom1504** [comment]
last progress on this https://github.com/roblabla/prismarine-chunk/commits/master

This issue is 8 months old, might be time to solve it... (blocking mineflayer and flying-squid for minecraft >=1.9)

**Comment by Flynnn** [comment]
RE: The WIP you did. I had a go at completing it:

https://gist.github.com/Flynnn/035c17f67158154220db7971e34314b2

Seems to work! It converts the new 1.9 raw chunk data back to the format being read by the 1.8 version of prismarine-chunk. Not the most ideal solution, but it appears to work. Histogram reports  76% air, 14% stone, 6% water, 1% bedrock, and less than 1% of dirt, lava, gravel, gold ore, iron ore, coal ore, and redstone ore.

I'm gonna go ahead and integrate this into a fork of prismarine-chunk.

**Comment by mhsjlw** [comment]
👍 Good luck! Keep us updated

**Comment by Flynnn** [comment]
AFAICT this should be good: https://github.com/Flynnn/prismarine-chunk But I'd like to wait until someone is able to really test it before doing a pull request

**Comment by polkovnikov-ph** [comment]
@Flynnn Great job! I'll try it right now.

**Comment by rom1504** [comment]
finally done thanks to @Flynnn

**Comment by Flynnn** [comment]
Most excellent! Thanks for al lthe help, @rom1504, @mhsjlw
