### ISSUE TITLE
Have a faster 1.9 chunk implementation

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/prismarine-chunk#27]
#18 is needed first, to check the actual times
Then there are several ways to do it : 
* convert the buffer in a faster format
* just store the buffer as is and access it

Something very easy to do and a bit of a hack might be a "lazy" option : just store the buffer as is and only actually convert it if a get* or set* gets called.
It might be useful for mineflayer for example, where only the chunk where the bot is, is actually really needed.

**Comment by rom1504** [comment]
optimized a bit now. Probably can still be faster though.

**Comment by mhsjlw** [comment]
We could always go native 😄

**Comment by rom1504** [comment]
well... it would really be coded in js anymore...
I'm pretty sure we can get decent perfs in js

**Comment by rom1504** [comment]
one way to avoid the problem altogether is simply to store the result of dump and recompute that at each change (possibly using something start to bundle some)
could be done either as a helper here (to support all versions) or directly in prismarine-word

Would prob make dumping hence flying-squid much faster

for loading it would be possible to have a similar smart mode where you only store the "buffer to process" and just schedule its processing for later except if it is asked (with a getBlock or such thing)
would make mineflayer faster

also note that pchunk 1.9 depends on protodef, so using node-protodefc would prob help

**Comment by rom1504** [comment]
install mcp and do the same as vanilla

**Comment by mhsjlw** [comment]
Can we really port it over legally?

**Comment by rom1504** [comment]
is it ever illegal to port something to another language ?

**Comment by rom1504** [comment]
Algorithm can't be copyrighted in Europe.
About code, well it won't be the same in js really.
Anyway, it's not like we're distributing the vanilla code directly or
something, I think it's ok.
Worse case we can look at glowstone which apparently has a similar to
vanilla implementation too.

**Comment by mhsjlw** [comment]
:+1:

**Comment by Karang** [comment]
Seems fast enough to me. Can this be closed ?
