### ISSUE TITLE
1.13 support

### ISSUE THREAD

**Issue by AnthonyTsang** [PrismarineJS/prismarine-chunk#46]
[Update notes](https://wiki.vg/index.php?title=Pre-release_protocol&oldid=14150#Chunk_Data)

There are some updates on the chunk data definition including the removal for direct palette and the change of biome data type.

**Comment by Bjornskjald** [comment]
1.13 chunks read with prismarine-chunk 1.12 end up weird, no errors or anything but the whole chunk is randomly grass, cobblestone and air. Is there a newer version I could test at the moment?

**Comment by plexigras** [comment]
there is pr https://github.com/PrismarineJS/prismarine-chunk/pull/47

**Comment by AnthonyTsang** [comment]
@plexigras thx for tagging. 

@Bjornskjald Yes, I am working on it. The PR supports part of the update but your case, the random data, is still exists. Still trying to understand what is changed.

**Comment by Bjornskjald** [comment]
Would it help if I send some example chunks with known data?

**Comment by AnthonyTsang** [comment]
Thx, i have a server running 1.13

**Comment by leumasme** [comment]
Is this still being worked on? Would really love it.

**Comment by rom1504** [comment]
@leumasme see https://github.com/PrismarineJS/prismarine-chunk/pull/47

AFAIK nobody is working on it at the moment

**Comment by rom1504** [comment]
done
