### ISSUE TITLE
1.14 Support

### ISSUE THREAD

**Issue by Gaz492** [PrismarineJS/prismarine-chunk#61]
Are there any plans on adding 1.14 support?

**Comment by rom1504** [comment]
yes but prerequisite it's #57  (since 1.13 and 1.14 have similar format)

**Comment by PinkFlufflyLlama** [comment]
I'll be doing this, It could take a while because I have some other thing going on too  

> https://github.com/PrismarineJS/prismarine-chunk/issues/57#issuecomment-594141086

**Comment by rom1504** [comment]
this could be done easily enough by adapting (/make a bit more generic) the new 1.13 implem

**Comment by PinkFlufflyLlama** [comment]
Ok, I have much less time than I did before so I'm not going to be able to work on this anymore
