### ISSUE TITLE
Wrong StateId from magma_block

### ISSUE THREAD

**Issue by kamesa7** [PrismarineJS/prismarine-chunk#63]
1.13
There are blocks that stateId is over 8192, but getBlockStateId() returns under 8192.
So magma_block looks stone block.
`    return this.data.readUInt16LE(cursor) % 8192  `
I removed `% 8192` to try but it seems to work well.

**Comment by rom1504** [comment]
What do you mean exactly ?
Does removing 8192 just make the current implementation work ?
How did you test that ?

**Comment by kamesa7** [comment]
In the vanilla debug world, I looked at blocks using bot.blockAt() in order. Block names is the correct name until third frosted_ice(stateId 8189-8192), but fourth is "air", magma_block(8193) is "stone" and nether_wart_block(8194) is "grinite", etc...
I don't know why it returns mod 8192.
Removing 8192 just make the current implementation work.
![2019-09-30_22 37 57](https://user-images.githubusercontent.com/35834522/65884040-161b4000-e3d3-11e9-864b-9565225b5940.png)

**Comment by rom1504** [comment]
Ok that's very interesting if true. I'll give your branch a try

**Comment by rom1504** [comment]
it's fixed in now merged new implem of 1.13
