### ISSUE TITLE
prettier support

### ISSUE THREAD

**Issue by hornta** [PrismarineJS/prismarine-chunk#64]
StandardJS doesn't work with Prettier out of the box. I've had to disable semicolons and doublequotes in prettier options but there are still cases where "Missing space before function parentheses." isn't configurable with Prettier. 

I've tried to used https://github.com/sheerun/prettier-standard but I failed to have it work with the "Format on save" feature in vscode.

Can we use Prettier instead for code formatting while keeping the other rules of standardjs(which in reality is the ones that really matter)?

**Comment by rom1504** [comment]
Hello
Why don't you use the standardjs plugin for vscode ?

**Comment by hornta** [comment]
Didn’t know that one existed. Thanks. It might help me relax. I was going crazy without formatting according to linting rules :-)
