### ISSUE TITLE
`minecraft-data` should be in dependencies

### ISSUE THREAD

**Issue by ianpaschal** [PrismarineJS/prismarine-chunk#76]
Right?

Now it's in `devDependencies` which _looks_ like a mistake to me. I'm happy to make PR as its only a 1 minute change but I wanted to confirm beforehand.

**Comment by rom1504** [comment]
Yeah we used to only depend on prismarine-block so it didn't need to be a
dep. Now it seems we are using it directly so it should be a dependency
indeed
