### ISSUE TITLE
Implement the 0x21 map_chunk bitmap

### ISSUE THREAD

**Issue by wtfaremyinitials** [PrismarineJS/prismarine-chunk#8]
Minecraft network packet 0x21 map_chunk allows for a bitmap to specify which 16x16x16 minichunks are included and which are left out to be filled with air. Currently there is no way of using this, and the entirety of the chunk must be sent over the wire.

**Comment by rom1504** [comment]
This is needed : sending whole columns to a client is way too slow.

**Comment by rom1504** [comment]
see http://wiki.vg/SMP_Map_Format#Bitmasks

**Comment by rom1504** [comment]
Right, I'm probably going to do that next: sending whole columns saturate my 1MB/s connection for a few minutes, which means no other packets are received during that time (and adding a 100ms sleep between each map packet makes loading of chunks really slow)

**Comment by roblabla** [comment]
stay away from bulk, it's going to be deprecated in 1.9

**Comment by rom1504** [comment]
Yeah indeed.

**Comment by rom1504** [comment]
The main difficulty here is these cursor functions https://github.com/PrismarineJS/prismarine-chunk/blob/master/src/chunk.js#L19

**Comment by rom1504** [comment]
Hmm, so, it might be that nmp server doesn't compress packets (see https://github.com/PrismarineJS/node-minecraft-protocol/blob/c55865ef33bc6ba871364a5beddf1c6f091544f8/src/createServer.js#L203 ).

So this issue might not be that much urgent, I think something to do would be connecting with mineflayer to a vanilla server and see whether the vanilla server uses that bipmap or not.

**Comment by rom1504** [comment]
Anyway we want to represent things internally, dump *and* load should have a bitmask argument, to handle the fact the mc server send it that way.

**Comment by filfat** [comment]
bump this :)

**Comment by rom1504** [comment]
dependent on #19
