### ISSUE TITLE
How similar are mineflayer chunk handling and prismarine-chunk ?

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/prismarine-chunk#9]
It might be nice to somehow use prismarine-chunk inside mineflayer.

**Comment by wtfaremyinitials** [comment]
Here's where I think we should use prismarine-chunk in mineflayer https://github.com/andrewrk/mineflayer/blob/master/lib/plugins/blocks.js.

**Comment by rom1504** [comment]
So apparently (https://github.com/mhsjlw/craftyjs), this module actually work.
See if that can be easily integrated into mineflayer.

**Comment by rom1504** [comment]
Mineflayer handles the world in column of 1x256x1. Is it more efficient the way prismarine-chunk want to do it (16x256x16) ?

**Comment by rom1504** [comment]
tracked in https://github.com/andrewrk/mineflayer/issues/334
